@baseUrl = http://localhost:3001

###

POST {{baseUrl}}/api/sessions
Content-Type: application/json

{
	"username": "alessandro.ruggiero.dev@gmail.com",
	"password": "password"
}

###

GET {{baseUrl}}/api/sessions/current

###

DELETE {{baseUrl}}/api/sessions/current

###

GET {{baseUrl}}/api/sessions/current

###

POST {{baseUrl}}/api/sessions
Content-Type: application/json

{
	"username": "alessandro.ruggiero.dev@gmail.com",
	"password": "wrong"
}

###
GET {{baseUrl}}/api/network

###
POST {{baseUrl}}/api/games

###
GET {{baseUrl}}/api/games/2

###
POST {{baseUrl}}/api/games/2/answer
Content-Type: application/json

{
	"connections": [19, 18, 17, 16, 15, 14, 13, 1]
}

###
POST {{baseUrl}}/api/games/1/answer
Content-Type: application/json

{
	"connections": [99, 100]
}

###
# should return 422
POST {{baseUrl}}/api/games/1/answer
Content-Type: application/json

{
	"connections": []
}

###
GET {{baseUrl}}/api/leaderboard

###
GET {{baseUrl}}/api/leaderboard?count=5

###
# should return 422
GET {{baseUrl}}/api/leaderboard?count=0

###
# should return 422
GET {{baseUrl}}/api/leaderboard?count=-1

###
# should return 422
GET {{baseUrl}}/api/leaderboard?count=abc

###
# should return 422
GET {{baseUrl}}/api/leaderboard?count=1000